### ISSUE TITLE
HTTP dissector not working properly (?)

### ISSUE THREAD

**Issue by craig** [haka-security/haka#14]
I'm using the latest git version of haka.

Config: 
   # /etc/haka/haka.conf
   [general]
   configuration = "/usr/local/share/haka/sample/stats/stats.lua"
   
   [packet]
   module = "packet/pcap"
   
   interfaces = "eth1"
   
   [log]
   module = "log/syslog"
   
   [alert]
   module = "alert/elasticsearch"
   
   elasticsearch_server = "http://s100240.rz.babiel.com:9200"
   geoip_database = "/usr/share/GeoIP/GeoIP.dat"

Added this on top of /usr/local/share/haka/sample/stats/stats.lua:

   require('misc/hakabana').initialize{
       elasticsearch = {
           host = "127.0.0.1",
           port = 9200,
       },
       geoip_data = '/usr/share/GeoIP/GeoIP.dat'
   }

I'm using hakabana as the frontend; however "HTTP User-Agents" logs all sorts of bots, but not regular HTTP clients. To verify that it's not my setup, I've used ngrep to do: "ngrep -d eth1 -W byline Mozilla" and it shows *lots* of queries from Mozilla.

**Comment by diasdavid** [comment]
Me and @tdantas are trying to run the script available on [4. On-the-fly modifications](http://doc.haka-security.org/haka/release/v0.2.2/doc/user/workshop/modif.html) but without success. tcp rules seem to work fine, but when it comes to http rules, the rule doesn't seem to catch even one packet.

**Comment by paulfariello** [comment]
Could you give us more information on the setup you have ?
What packet module are you using, packet/nfqueue, packet/pcap ?

Are you sure you have put the install rule in your config ?
```lua
http.install_tcp_rule(80)
```

**Comment by diasdavid** [comment]
@paulfariello we're using the .iso from http://www.haka-security.org/download/haka.html and using the rule available on the tutorial. Does this help? Can you replicate it?

**Comment by paulfariello** [comment]
@diasdavid running haka with the following configuration works like a charm.
```
[general]
configuration = "/home/user/Downloads/blurring-the-web.lua"
[packet]
module = "packet/nfqueue"
interfaces = "lo"
```

Can you ensure: 
  * you configured haka on the right interface
  * packet module is set to "packet/nfqueue"
  * haka use the rules file given at http://doc.haka-security.org/haka/release/v0.2.2/_downloads/blurring-the-web.lua

**Comment by paulfariello** [comment]
No news on this issue since more than 11 month. Closing it. Feel free to reopen if you have some news.
