### ISSUE TITLE
Building issues on OpenSUSE 13.2

### ISSUE THREAD

**Issue by uhei** [haka-security/haka#16]
Building haka fails on OpenSUSE 13.2 due to two problems.

* function clear_error() in error.h is defined without any parameter. In src/haka/ctl.c line 125 there is a call of this function with parameter errno.
This results in error:
```
haka_0.2.2_source/src/haka/ctl.c:125:3: error: call to function ‘clear_error’ without a real prototype [-Werror=unprototyped-calls]
   messagef(HAKA_LOG_DEBUG, MODULE, "failed to create thread: %s", clear_error(errno));
   ^
In file included from haka_0.2.2_source/src/haka/ctl.c:13:0:
haka_0.2.2_source/include/haka/error.h:43:13: note: ‘clear_error’ was declared here
 const char *clear_error();
```
Fix is to remove errno in the clear_error() function call

* function prepare_ctl_server() is defined without any parameter in src/haka/ctl.h.
This results in error:
```
src/haka/haka.c:509:2: error: call to function ‘prepare_ctl_server’ without a real prototype [-Werror=unprototyped-calls]
  ret = prepare_ctl_server(ctl_file_path);
  ^
In file included from src/haka/haka.c:29:0:
src/haka/ctl.h:9:6: note: ‘prepare_ctl_server’ was declared here
 bool prepare_ctl_server();
```
Fix is to define the parameter in ctl.h

**Comment by mtalbi** [comment]
Thank you for reporting this bug.
We will try to set up a build environment on OpenSuse and fix the bugs as soon as possible.
Regards,

**Comment by paulfariello** [comment]
We just fixed the issues you have reported. You can find them at d1da95b032a9919fdafdecfe183ba7e97c0451eb.

Regards,
