### ISSUE TITLE
Compile Issue Under Ubuntu 14.04

### ISSUE THREAD

**Issue by FusionFC** [haka-security/haka#20]
Compiling v0.2.2 under Ubuntu 14.04.2 LTS (gcc v4.8.2) causes several compilation errors.

haka/lib/haka/state_machine.c: In function ‘state_machine_enter_state’:
haka/lib/haka/state_machine.c:410:7: error: format not a string literal and no format arguments [-Werror=format-security]
       LOG_ERROR(MODULE, clear_error());
       ^
haka/lib/haka/state_machine.c:422:7: error: format not a string literal and no format arguments [-Werror=format-security]
       LOG_ERROR(MODULE, clear_error());

Similarly there are issues in:

src/haka/app.c: 148, 162, 179
src/haka/thread.c: 251, 258, 267, 287, 296, 477, 492
src/haka/haka.c: 256, 297
src/haka/ctl.c: 100, 106, 345, 567
src/haka/hakapcap.c: 95
src/hakactl/commands.c: 195

**Comment by paulfariello** [comment]
thanks for reporting the issue. I just pushed a fix in hotfix/0.2.3 (58f0c787cc58eeff89e159033ece1e153fa6c63b).

Please tell me if this works for you so I can close this issue.

**Comment by MalloZup** [comment]
Hi Paul. i have the same version Ubuntu and Gcc like FusionFc. I had the some problem. Just compiled the new fix-haka and i got others errors by compiling: 

Scanning dependencies of target pcre
[  3%] Building C object modules/regexp/pcre/CMakeFiles/pcre.dir/main.c.o
haka/modules/regexp/pcre/main.c:14:8: error: type defaults to ‘int’ in declaration of ‘REGISTER_LOG_SECTION’ [-Werror=implicit-int]
 static REGISTER_LOG_SECTION(pcre);
        ^
haka/modules/regexp/pcre/main.c: In function ‘workspace_grow’:
haka/modules/regexp/pcre/main.c:309:2: error: implicit declaration of function ‘LOG_DEBUG’ [-Werror=implicit-function-declaration]
  LOG_DEBUG(pcre, "growing PCRE workspace to %d int", sink->wscount);
  ^
haka/modules/regexp/pcre/main.c:309:12: error: expected expression before ‘pcre’
  LOG_DEBUG(pcre, "growing PCRE workspace to %d int", sink->wscount);
            ^
haka/modules/regexp/pcre/main.c: At top level:
haka/modules/regexp/pcre/main.c:14:8: error: ‘REGISTER_LOG_SECTION’ declared ‘static’ but never defined [-Werror=unused-function]
 static REGISTER_LOG_SECTION(pcre);
        ^
cc1: all warnings being treated as errors
make[2]: *** [modules/regexp/pcre/CMakeFiles/pcre.dir/main.c.o] Fehler 1
make[1]: *** [modules/regexp/pcre/CMakeFiles/pcre.dir/all] Fehler 2
=================
gcc flags are:
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.2-19ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix



Best regards,

**Comment by MalloZup** [comment]
Hi Paul, 

some news:

for the 1) error , better warning ( but in my version warnings are treats like error):
the static REGISTER_LOG_SECTION(pcre) in never used. So i just comment it and it´s work fine.

the 2) error it's a direct consequence of your changes into the fix version:
 
you have changed  LOG_DEBUG to messagef(HAKA_LOG_DEBUG, "engine", "lua remote ...
[haka/lib/haka/engine.c:292:]

but a lot of LOG_DEBUG still persist in the code: 

$ grep --include=\*.{c,h} -rnw 'haka' -e "LOG_DEBUG" 
=====
haka/modules/misc/elasticsearch/elasticsearch.c:317:	LOG_DEBUG(elasticsearch, "post successful: %s return %lu", url, ret_code);
haka/modules/packet/nfqueue/main.c:732:				LOG_DEBUG(nfqueue, "unknown verdict");
haka/modules/log/syslog/main.c:34:	LOG_DEBUG,
haka/modules/alert/elasticsearch/main.c:448:	LOG_DEBUG(elasticsearch, "using elasticsearch index %s",
haka/modules/alert/elasticsearch/main.c:452:	LOG_DEBUG(elasticsearch, "generating global id prefix %s",
haka/modules/protocol/ipv4/ipv4-network.c:71:		LOG_DEBUG(ipv4, "incorrect network mask");
haka/modules/protocol/ipv4/cnx.c:68:		LOG_DEBUG(conn, "%s connection %s:%u -> %s:%u",
=====

and the same scenario exist for the others LOG_ERROR, LOG_INFO,  LOG_FOO etc, etc.

ror: implicit declaration of function ‘LOG_WARNING’ [-Werror=implicit-function-declaration]
    LOG_WARNING(pcap, "%s", errbuf);
=========

I hope this can help,
best regard

**Comment by paulfariello** [comment]
Hi MalloZup,

thanks for reporting the issue. Unfortunately I can't reproduce 1) on Ubuntu 14.04.2. Can you give us the output of the ``cmake`` initial command on a clean workspace ?

Concerning 2), ``LOG_DEBUG`` is defined in ``include/haka/log.h``. Could you check that you really have a clean checkout of Haka (and a clean workspace) ? If this is the case the output of the initial ``cmake`` command should gives us some clues.

Regards,

**Comment by MalloZup** [comment]
Hi Paul, 
i had installed haka from the source and new version of the Linux kernel. Few days ago, i had other problems with other libraries, so i think the problem was not from haka. Now i have haka on ubuntu, installed from the new *.deb packet and it seems to work for me.  So when i have time i will check again the installation from source. Thanks for the reply,

best regards

**Comment by paulfariello** [comment]
Ok thanks.
I'll close the issue for now. Feel free to reopen it if you have the issue again.
