### ISSUE TITLE
Minor CMake warning

### ISSUE THREAD

**Issue by victoredwardocallaghan** [haka-security/haka#22]
Hi,

I just wanted to make note of this CMake warning:
Also the build instructions should include 'geoip-devel' on the list of packages for Fedora.

-- Found LibGeoIP: /usr/lib64/libGeoIP.so  
CMake Warning (dev) at modules/CMakeLists.txt:34 (target_link_libraries):
  Policy CMP0023 is not set: Plain and keyword target_link_libraries
  signatures cannot be mixed.  Run "cmake --help-policy CMP0023" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The keyword signature for target_link_libraries has already been used with
  the target "geoip".  All uses of target_link_libraries with a target should
  be either all-keyword or all-plain.

  The uses of the keyword signature are here:

   * modules/misc/geoip/CMakeLists.txt:19 (target_link_libraries)

Call Stack (most recent call first):
  modules/misc/geoip/CMakeLists.txt:25 (INSTALL_MODULE)
This warning is for project developers.  Use -Wno-dev to suppress it.

[edward@tinypuppy workspace]$ cmake --help-policy CMP0023
CMP0023
-------

Plain and keyword target_link_libraries signatures cannot be mixed.

CMake 2.8.12 introduced the target_link_libraries signature using the
PUBLIC, PRIVATE, and INTERFACE keywords to generalize the LINK_PUBLIC
and LINK_PRIVATE keywords introduced in CMake 2.8.7.  Use of
signatures with any of these keywords sets the link interface of a
target explicitly, even if empty.  This produces confusing behavior
when used in combination with the historical behavior of the plain
target_link_libraries signature.  For example, consider the code:

::

 target_link_libraries(mylib A)
 target_link_libraries(mylib PRIVATE B)

After the first line the link interface has not been set explicitly so
CMake would use the link implementation, A, as the link interface.
However, the second line sets the link interface to empty.  In order
to avoid this subtle behavior CMake now prefers to disallow mixing the
plain and keyword signatures of target_link_libraries for a single
target.

The OLD behavior for this policy is to allow keyword and plain
target_link_libraries signatures to be mixed.  The NEW behavior for
this policy is to not to allow mixing of the keyword and plain
signatures.

This policy was introduced in CMake version 2.8.12.  CMake version
3.0.2 warns when the policy is not set and uses OLD behavior.  Use
the cmake_policy command to set it to OLD or NEW explicitly.

Kind Regards,
Edward

**Comment by paulfariello** [comment]
Thanks for reporting.

This have been fixed with 88f2694dd6cb6d860576b630d77d9276eadf091b.
