### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [haka-security/haka#23]
I would like to point out that identifiers like "[`_HAKA_LOG_H`](https://github.com/haka-security/haka/blob/322965f6716bccf3fc6e8a74dd579936b572c016/include/haka/log.h#L10)" and "[`_HAKA_PACKET_H`](https://github.com/haka-security/haka/blob/8d9566cad6c8bd6e1fb40ec6629609003d887fa6/include/haka/packet.h#L10)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by paulfariello** [comment]
Hi elfring,

thanks for reporting the issue. The fix will be pushed in develop as soon as possible.

**Comment by elfring** [comment]
Would it be better if this issue will only be closed after it was fixed?

**Comment by paulfariello** [comment]
You are right, the fix is commited in our internal repository. I'll update the issue when we will push it in github.

**Comment by paulfariello** [comment]
This have been fixed by 7098ed5c67539fc7c417aa9a1362573a9f03fa52.

**Comment by paulfariello** [comment]
This have been fixed by 7098ed5c67539fc7c417aa9a1362573a9f03fa52.

**Comment by elfring** [comment]
I find [an other commit more appropriate](https://github.com/haka-security/haka/commit/7a1d2ccbba833b23af2551f959d45e7cbe2cc250) for example.
Thanks for [your improvement of affected identifiers](https://github.com/haka-security/haka/commit/776fe1d6b94c7dcec8f5cc142f20026c1ee43bf2).
