### ISSUE TITLE
Build issue on Centos 6

### ISSUE THREAD

**Issue by gugansankar** [haka-security/haka#27]
I'm getting below error when I do compile haka on Centos 6.  Is there any rpm package available for Centos ?. If so, please share the file, that would be so helpful for installing haka.

[ 31%] Building C object lib/haka/CMakeFiles/libhaka.dir/lua/hakainitLUA_wrap.c.o
[ 32%] Building C object lib/haka/CMakeFiles/libhaka.dir/lua/hakaLUA_wrap.c.o
cc1: warnings being treated as errors
/root/SETUP/haka/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_alert_method_ref_set’:
/root/SETUP/haka/make/lib/haka/lua/hakaLUA_wrap.c:2461: error: dereferencing pointer ‘arg1.998’ does break strict-aliasing rules
/root/SETUP/haka/make/lib/haka/lua/hakaLUA_wrap.c:2471: error: dereferencing pointer ‘arg1.998’ does break strict-aliasing rules
/root/SETUP/haka/make/lib/haka/lua/hakaLUA_wrap.c:2478: error: dereferencing pointer ‘arg1.998’ does break strict-aliasing rules
/root/SETUP/haka/make/lib/haka/lua/hakaLUA_wrap.c:12380: note: initialized from here
make[2]: **\* [lib/haka/CMakeFiles/libhaka.dir/lua/hakaLUA_wrap.c.o] Error 1
make[1]: **\* [lib/haka/CMakeFiles/libhaka.dir/all] Error 2
make: **\* [all] Error 2

**Comment by gugansankar** [comment]
Any solution for this error message ?.

**Comment by gugansankar** [comment]
no one had hit with this problem ?.

**Comment by paulfariello** [comment]
Hi,

which version of swig are you using ? Haka requires swig >= 2 but it seems only swig 1.3.40 is available for Centos 6.

**Comment by paulfariello** [comment]
Closing the issue as there is no news on this since 1 month.
Feel free to reopen.
