### ISSUE TITLE
Build issue on Fedora 22

### ISSUE THREAD

**Issue by sgros** [haka-security/haka#28]
Hi!

While trying to compile haka on Fedora 22 I get a bunch of the following errors (actually, warnings treated as errors):

/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘struct_vbuffer_iterator__insert’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:3314:5: error: ‘return’ with no value, in function returning non-void [-Werror]
     return;
     ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:3319:5: error: ‘return’ with no value, in function returning non-void [-Werror]
     return;
     ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘struct_vbuffer_iterator_sub__SWIG_1’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:3384:12: error: implicit declaration of function ‘vbuffer_iterator_sub__SWIG_0’ [-Werror=implicit-function-declaration]
     return vbuffer_iterator_sub__SWIG_0(self, -1, split);
            ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:3384:12: error: return makes pointer from integer without a cast [-Werror=int-conversion]
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:3387:12: error: return makes pointer from integer without a cast [-Werror=int-conversion]
     return vbuffer_iterator_sub__SWIG_0(self, -1, split);
            ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘struct_vbuffer_iterator_move_to__SWIG_1’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:3403:4: error: implicit declaration of function ‘vbuffer_iterator_move_to__SWIG_0’ [-Werror=implicit-function-declaration]
    vbuffer_iterator_move_to__SWIG_0(self, &iter->super);
    ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘struct_vbuffer_iterator_blocking_insert’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:3435:166: error: implicit declaration of function ‘vbuffer_iterator__insert’ [-Werror=implicit-function-declaration]
 SWIGINTERN struct vbuffer_sub *struct_vbuffer_iterator_blocking_insert(struct vbuffer_iterator_blocking *self,struct vbuffer *data){ return vbuffer_iterator__insert(&self->super, data); }
                                                                                                                                                                      ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:3435:166: error: return makes pointer from integer without a cast [-Werror=int-conversion]
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘struct_vbuffer_iterator_blocking_copy’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:3437:148: error: implicit declaration of function ‘vbuffer_iterator__copy’ [-Werror=implicit-function-declaration]
 SWIGINTERN struct vbuffer_iterator *struct_vbuffer_iterator_blocking_copy(struct vbuffer_iterator_blocking *self){ return vbuffer_iterator__copy(&self->super); }
                                                                                                                                                    ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:3437:148: error: return makes pointer from integer without a cast [-Werror=int-conversion]
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘struct_vbuffer_iterator_blocking_move_to__SWIG_0’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:3438:169: error: ‘return’ with a value, in function returning void [-Werror]
 SWIGINTERN void struct_vbuffer_iterator_blocking_move_to__SWIG_0(struct vbuffer_iterator_blocking *self,struct vbuffer_iterator *iter){ return vbuffer_iterator_move_to__SWIG_0(&self->super, iter); }
                                                                                                                                                                         ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘struct_vbuffer_iterator_blocking_move_to__SWIG_1’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:3439:178: error: implicit declaration of function ‘vbuffer_iterator_move_to__SWIG_1’ [-Werror=implicit-function-declaration]
 SWIGINTERN void struct_vbuffer_iterator_blocking_move_to__SWIG_1(struct vbuffer_iterator_blocking *self,struct vbuffer_iterator_blocking *iter){ return vbuffer_iterator_move_to__SWIG_1(&self->super, iter); }
                                                                                                                                                                                  ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:3439:178: error: ‘return’ with a value, in function returning void [-Werror]
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘struct_vbuffer_sub_sub__SWIG_1’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:3556:12: error: implicit declaration of function ‘vbuffer_sub_sub__SWIG_0’ [-Werror=implicit-function-declaration]
     return vbuffer_sub_sub__SWIG_0(self, offset, -1);
            ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:3556:12: error: return makes pointer from integer without a cast [-Werror=int-conversion]
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘struct_vbuffer_sub_pos__SWIG_1’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:3584:41: error: implicit declaration of function ‘vbuffer_sub_pos__SWIG_0’ [-Werror=implicit-function-declaration]
    if (strcmp(pos, "begin") == 0) return vbuffer_sub_pos__SWIG_0(self, 0);
                                         ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:3584:41: error: return makes pointer from integer without a cast [-Werror=int-conversion]
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:3585:44: error: return makes pointer from integer without a cast [-Werror=int-conversion]
    else if (strcmp(pos, "end") == 0) return vbuffer_sub_pos__SWIG_0(self, -1);
                                            ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘struct_vbuffer_pos__SWIG_1’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:3681:41: error: implicit declaration of function ‘vbuffer_pos__SWIG_0’ [-Werror=implicit-function-declaration]
    if (strcmp(pos, "begin") == 0) return vbuffer_pos__SWIG_0(self, 0);
                                         ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:3681:41: error: return makes pointer from integer without a cast [-Werror=int-conversion]
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:3682:44: error: return makes pointer from integer without a cast [-Werror=int-conversion]
    else if (strcmp(pos, "end") == 0) return vbuffer_pos__SWIG_0(self, -1);
                                            ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘struct_vbuffer_sub__SWIG_1’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:3706:12: error: implicit declaration of function ‘vbuffer_sub__SWIG_0’ [-Werror=implicit-function-declaration]
     return vbuffer_sub__SWIG_0(self, offset, -1);
            ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:3706:12: error: return makes pointer from integer without a cast [-Werror=int-conversion]
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘struct_vbuffer_sub__SWIG_2’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:3714:11: error: return makes pointer from integer without a cast [-Werror=int-conversion]
    return vbuffer_sub__SWIG_0(self, 0, -1);
           ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_time___getitem’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:4864:3: error: implicit declaration of function ‘struct_time___getitem’ [-Werror=implicit-function-declaration]
   struct_time___getitem(arg1,arg2);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_time___setitem’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:4903:3: error: implicit declaration of function ‘struct_time___setitem’ [-Werror=implicit-function-declaration]
   struct_time___setitem(arg1,arg2,arg3);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_vbuffer_iterator_mark’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:5162:3: error: implicit declaration of function ‘struct_vbuffer_iterator_mark’ [-Werror=implicit-function-declaration]
   struct_vbuffer_iterator_mark(arg1,arg2);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_vbuffer_iterator_unmark’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:5192:3: error: implicit declaration of function ‘struct_vbuffer_iterator_unmark’ [-Werror=implicit-function-declaration]
   struct_vbuffer_iterator_unmark(arg1);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_vbuffer_iterator_advance’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:5226:17: error: implicit declaration of function ‘struct_vbuffer_iterator_advance’ [-Werror=implicit-function-declaration]
   result = (int)struct_vbuffer_iterator_advance(arg1,arg2);
                 ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_vbuffer_iterator_available’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:5367:17: error: implicit declaration of function ‘struct_vbuffer_iterator_available’ [-Werror=implicit-function-declaration]
   result = (int)struct_vbuffer_iterator_available(arg1);
                 ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_vbuffer_iterator_split’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:5788:3: error: implicit declaration of function ‘struct_vbuffer_iterator_split’ [-Werror=implicit-function-declaration]
   struct_vbuffer_iterator_split(arg1);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_vbuffer_iterator___getitem’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:5854:3: error: implicit declaration of function ‘struct_vbuffer_iterator___getitem’ [-Werror=implicit-function-declaration]
   struct_vbuffer_iterator___getitem(arg1,arg2);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_vbuffer_iterator___setitem’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:5893:3: error: implicit declaration of function ‘struct_vbuffer_iterator___setitem’ [-Werror=implicit-function-declaration]
   struct_vbuffer_iterator___setitem(arg1,arg2,arg3);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_vbuffer_iterator_blocking_meter_set’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:6399:3: error: implicit declaration of function ‘struct_vbuffer_iterator_blocking_meter_set’ [-Werror=implicit-function-declaration]
   struct_vbuffer_iterator_blocking_meter_set(arg1,arg2);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_vbuffer_iterator_blocking_meter_get’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:6430:17: error: implicit declaration of function ‘struct_vbuffer_iterator_blocking_meter_get’ [-Werror=implicit-function-declaration]
   result = (int)struct_vbuffer_iterator_blocking_meter_get(arg1);
                 ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_vbuffer_iterator_blocking___getitem’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:6527:3: error: implicit declaration of function ‘struct_vbuffer_iterator_blocking___getitem’ [-Werror=implicit-function-declaration]
   struct_vbuffer_iterator_blocking___getitem(arg1,arg2);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_vbuffer_iterator_blocking___setitem’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:6566:3: error: implicit declaration of function ‘struct_vbuffer_iterator_blocking___setitem’ [-Werror=implicit-function-declaration]
   struct_vbuffer_iterator_blocking___setitem(arg1,arg2,arg3);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_vbuffer_sub_size’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:7029:17: error: implicit declaration of function ‘struct_vbuffer_sub_size’ [-Werror=implicit-function-declaration]
   result = (int)struct_vbuffer_sub_size(arg1);
                 ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_vbuffer_sub_isflat’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:7172:18: error: implicit declaration of function ‘struct_vbuffer_sub_isflat’ [-Werror=implicit-function-declaration]
   result = (bool)struct_vbuffer_sub_isflat(arg1);
                  ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_vbuffer_sub___getitem__SWIG_1’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:7866:3: error: implicit declaration of function ‘struct_vbuffer_sub___getitem’ [-Werror=implicit-function-declaration]
   struct_vbuffer_sub___getitem(arg1,arg2);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_vbuffer_sub___setitem__SWIG_1’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:7959:3: error: implicit declaration of function ‘struct_vbuffer_sub___setitem’ [-Werror=implicit-function-declaration]
   struct_vbuffer_sub___setitem(arg1,arg2,arg3);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_vbuffer___getitem__SWIG_1’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:8927:3: error: implicit declaration of function ‘struct_vbuffer___getitem’ [-Werror=implicit-function-declaration]
   struct_vbuffer___getitem(arg1,arg2);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_vbuffer___setitem__SWIG_1’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:9035:3: error: implicit declaration of function ‘struct_vbuffer___setitem’ [-Werror=implicit-function-declaration]
   struct_vbuffer___setitem(arg1,arg2,arg3);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_vbuffer_stream_finish’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:9295:3: error: implicit declaration of function ‘struct_vbuffer_stream_finish’ [-Werror=implicit-function-declaration]
   struct_vbuffer_stream_finish(arg1);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_vbuffer_stream___getitem’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:9497:3: error: implicit declaration of function ‘struct_vbuffer_stream___getitem’ [-Werror=implicit-function-declaration]
   struct_vbuffer_stream___getitem(arg1,arg2);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_vbuffer_stream___setitem’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:9551:3: error: implicit declaration of function ‘struct_vbuffer_stream___setitem’ [-Werror=implicit-function-declaration]
   struct_vbuffer_stream___setitem(arg1,arg2,arg3);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_vbuffer_sub_stream___getitem’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:9931:3: error: implicit declaration of function ‘struct_vbuffer_sub_stream___getitem’ [-Werror=implicit-function-declaration]
   struct_vbuffer_sub_stream___getitem(arg1,arg2);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_vbuffer_sub_stream___setitem’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:9985:3: error: implicit declaration of function ‘struct_vbuffer_sub_stream___setitem’ [-Werror=implicit-function-declaration]
   struct_vbuffer_sub_stream___setitem(arg1,arg2,arg3);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_packet_data_get’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:11089:12: error: implicit declaration of function ‘struct_packet_data_get’ [-Werror=implicit-function-declaration]
   result = struct_packet_data_get(arg1);
            ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:11089:10: error: incompatible types when assigning to type ‘struct lua_ref’ from type ‘int’
   result = struct_packet_data_get(arg1);
          ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_packet_drop’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:11505:3: error: implicit declaration of function ‘struct_packet_drop’ [-Werror=implicit-function-declaration]
   struct_packet_drop(arg1);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_alert_node___getitem’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:11792:3: error: implicit declaration of function ‘struct_alert_node___getitem’ [-Werror=implicit-function-declaration]
   struct_alert_node___getitem(arg1,arg2);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_alert_node___setitem’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:11831:3: error: implicit declaration of function ‘struct_alert_node___setitem’ [-Werror=implicit-function-declaration]
   struct_alert_node___setitem(arg1,arg2,arg3);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_alert_id___getitem’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:11956:3: error: implicit declaration of function ‘struct_alert_id___getitem’ [-Werror=implicit-function-declaration]
   struct_alert_id___getitem(arg1,arg2);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_alert_id___setitem’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:11995:3: error: implicit declaration of function ‘struct_alert_id___setitem’ [-Werror=implicit-function-declaration]
   struct_alert_id___setitem(arg1,arg2,arg3);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_alert___getitem’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:12689:3: error: implicit declaration of function ‘struct_alert___getitem’ [-Werror=implicit-function-declaration]
   struct_alert___getitem(arg1,arg2);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_alert___setitem’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:12728:3: error: implicit declaration of function ‘struct_alert___setitem’ [-Werror=implicit-function-declaration]
   struct_alert___setitem(arg1,arg2,arg3);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_state___getitem’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:13101:3: error: implicit declaration of function ‘struct_state___getitem’ [-Werror=implicit-function-declaration]
   struct_state___getitem(arg1,arg2);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_state___setitem’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:13140:3: error: implicit declaration of function ‘struct_state___setitem’ [-Werror=implicit-function-declaration]
   struct_state___setitem(arg1,arg2,arg3);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_state_machine_initial_set’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:13350:3: error: implicit declaration of function ‘struct_state_machine_initial_set’ [-Werror=implicit-function-declaration]
   struct_state_machine_initial_set(arg1,arg2);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_state_machine_initial_get’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:13381:28: error: implicit declaration of function ‘struct_state_machine_initial_get’ [-Werror=implicit-function-declaration]
   result = (struct state *)struct_state_machine_initial_get(arg1);
                            ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:13381:12: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
   result = (struct state *)struct_state_machine_initial_get(arg1);
            ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_state_machine___getitem’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:13478:3: error: implicit declaration of function ‘struct_state_machine___getitem’ [-Werror=implicit-function-declaration]
   struct_state_machine___getitem(arg1,arg2);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_state_machine___setitem’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:13517:3: error: implicit declaration of function ‘struct_state_machine___setitem’ [-Werror=implicit-function-declaration]
   struct_state_machine___setitem(arg1,arg2,arg3);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_state_machine_instance___getitem’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:13799:3: error: implicit declaration of function ‘struct_state_machine_instance___getitem’ [-Werror=implicit-function-declaration]
   struct_state_machine_instance___getitem(arg1,arg2);
   ^
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘_wrap_state_machine_instance___setitem’:
/data/Security/sources/haka.git/make/lib/haka/lua/hakaLUA_wrap.c:13838:3: error: implicit declaration of function ‘struct_state_machine_instance___setitem’ [-Werror=implicit-function-declaration]
   struct_state_machine_instance___setitem(arg1,arg2,arg3);
   ^
cc1: all warnings being treated as errors
lib/haka/CMakeFiles/libhaka.dir/build.make:965: recipe for target 'lib/haka/CMakeFiles/libhaka.dir/lua/hakaLUA_wrap.c.o' failed

**Comment by anthraxx** [comment]
ping, same issues on Arch Linux

**Comment by paulfariello** [comment]
The two first error have been fix with 185b0aee04d8d80997a6d250c5788ba058149981 see #29 .
I can't reproduce the following error on fedora 23. Can you give me your swig version and try a clean build with latest develop ?

**Comment by anthraxx** [comment]
works, thx :+1:
