### ISSUE TITLE
Build failing: lua/hakaLUA_wrap.c (-Werror)

### ISSUE THREAD

**Issue by anthraxx** [haka-security/haka#29]
Hi, build is failing on an Arch Linux, removing -Werror from  CMakeLists.txt works around the problem:

```
[ 30%] Building C object lib/haka/CMakeFiles/libhaka.dir/lua/hakaLUA_wrap.c.o
/build/haka-git/src/haka-git/make/lib/haka/lua/hakaLUA_wrap.c: In function ‘vbuffer_iterator__insert’:
/build/haka-git/src/haka-git/make/lib/haka/lua/hakaLUA_wrap.c:3314:5: error: ‘return’ with no value, in function returning non-void [-Werror]
     return;
     ^
/build/haka-git/src/haka-git/make/lib/haka/lua/hakaLUA_wrap.c:3319:5: error: ‘return’ with no value, in function returning non-void [-Werror]
     return;
     ^
cc1: all warnings being treated as errors
lib/haka/CMakeFiles/libhaka.dir/build.make:1005: recipe for target 'lib/haka/CMakeFiles/libhaka.dir/lua/hakaLUA_wrap.c.o' failed
make[2]: *** [lib/haka/CMakeFiles/libhaka.dir/lua/hakaLUA_wrap.c.o] Error 1
```

**Comment by paulfariello** [comment]
Hi,

thanks for reporting the issue. I remember having the same issue on arch linux a few weeks ago. But I can't reproduce it with current develop.

Could you tell us which function is throwing the error on lib/haka/lua/hakaLUA_wrap.c:3319 so I can check if the error is really fixed ?

**Comment by paulfariello** [comment]
Ok I've reproduced it. I have a fix. I'll run the full test suite tomorrow and push it to develop.

**Comment by paulfariello** [comment]
commit 185b0aee04d8d80997a6d250c5788ba058149981 and 50c5968b345f7c76ede00cb2103d47aa32d6648c fixes build on archlinux.

Can you confirm it ?

**Comment by anthraxx** [comment]
I can confirm, applying both patches do not require anymore to remove -Werror

works, thx :+1:
