### ISSUE TITLE
build on i686 broken (old patch from closed bugreport still not merged upstream)

### ISSUE THREAD

**Issue by anthraxx** [haka-security/haka#31]
Hey i686 is still broken as the patch from bugreport  #12 ( paulfariello/haka@6398e9f )

The patch works but is still not merged neither in develop nor in master since 1 year.

cheers
anthraxx

**Comment by paulfariello** [comment]
Thanks for reporting.
I just pushed the fix on develop. It will really be in next release.

**Comment by anthraxx** [comment]
works, thx :+1:
